/*
 * File: app/store/CusInvT1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HuhPtl.store.CusInvT1', {
    extend: 'Ext.data.Store',

    requires: [
        'HuhPtl.model.CusInv'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            model: 'HuhPtl.model.CusInv',
            storeId: 'CusInvT1',
            proxy: {
                type: 'rest',
                url: 'data/CusInvT1.php',
                reader: {
                    type: 'json',
                    root: 'Dta',
                    successProperty: 'Scs',
                    totalProperty: 'Ttl'
                }
            },
            sorters: [
                {
                    property: 'YRS'
                },
                {
                    property: 'MTH'
                },
                {
                    property: 'TYP'
                }
            ]
        }, cfg)]);
    }
});