/*
 * File: app/view/ChgObj.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.ChgObj', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.chgobj',

    border: 0,
    store: 'ChgObj',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'OBJNME',
                    text: 'Object'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'OBJTYP',
                    text: 'Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TRGENV',
                    text: 'Target'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'LCKUSR',
                    text: 'Developer'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PRSSTP',
                    text: 'Step'
                }
            ]
        });

        me.callParent(arguments);
    }

});