/*
 * File: app/view/DshBrd.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.DshBrd', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.dshbrd',

    requires: [
        'DshBrd.view.TrkPnl',
        'DshBrd.view.JobPnl',
        'DshBrd.view.DocPnl',
        'DshBrd.view.LnkPnl',
        'DshBrd.view.CogPnl'
    ],

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    border: 0,
                    items: [
                        {
                            xtype: 'button',
                            text: 'Edit',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Preferences'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'FltBtn',
                            text: 'Filter'
                        },
                        {
                            xtype: 'button',
                            text: 'Refresh'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            href: '../shared/usrsno.php',
                            text: 'Sign Out'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'trkpnl',
                            itemId: 'TrkTab',
                            title: 'Tracking '
                        },
                        {
                            xtype: 'jobpnl',
                            hidden: true,
                            itemId: 'JobTab',
                            title: 'Jobs '
                        },
                        {
                            xtype: 'docpnl',
                            hidden: true,
                            itemId: 'DocTab',
                            title: 'Documentation '
                        },
                        {
                            xtype: 'lnkpln',
                            hidden: true,
                            itemId: 'LnkTab',
                            title: 'Links '
                        },
                        {
                            xtype: 'cogpnl',
                            hidden: true,
                            itemId: 'CogTab',
                            title: 'Cognos '
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});