/*
 * File: app/view/JobLst.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.JobLst', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.joblst',

    border: 0,
    store: 'JobInf',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOB',
                    text: 'Job',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'USR',
                    text: 'User',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBNBRA',
                    text: 'Job Number',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SBS',
                    text: 'Subsystem',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SBSLIB',
                    text: 'Subsystem Library',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBTYP',
                    text: 'Job Typ',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBSTS',
                    text: 'Job Status',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBSTSACV',
                    text: 'Active Status',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});