/*
 * File: app/view/TrkMstDtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.TrkMstDtl', {
    extend: 'Ext.form.Panel',
    alias: 'widget.trkmstdtl',

    border: 0,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    trackResetOnLoad: true,

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            trackResetOnLoad: true
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 0.5,
                    height: 84,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            minWidth: 240,
                            padding: 5,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Identifier',
                                    labelWidth: 70,
                                    name: 'TrkIdn'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Status',
                                    labelWidth: 70,
                                    name: 'CllSts',
                                    displayField: 'CllSts',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'CllSts',
                                    typeAhead: true,
                                    valueField: 'CllSts'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Priority',
                                    labelWidth: 70,
                                    name: 'CllPri',
                                    displayField: 'CllPri',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'CllPri',
                                    typeAhead: true,
                                    valueField: 'CllPri'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            minWidth: 240,
                            items: [
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Type',
                                    labelWidth: 70,
                                    name: 'CllTyp',
                                    displayField: 'CllTyp',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'CllTyp',
                                    typeAhead: true,
                                    valueField: 'CllTyp'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Category',
                                    labelWidth: 70,
                                    name: 'CllCtg',
                                    displayField: 'CllCtg',
                                    queryMode: 'local',
                                    store: 'CllCtg',
                                    typeAhead: true,
                                    valueField: 'CllCtg'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Class',
                                    labelWidth: 70,
                                    name: 'CllCls'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            minWidth: 240,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'User',
                                    labelWidth: 70,
                                    name: 'UsrNme'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Email',
                                    labelWidth: 70,
                                    name: 'EmlAdrUsr'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                align: 'stretch',
                                padding: 5,
                                type: 'vbox'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    padding: 5,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'textareafield',
                            flex: 1,
                            margins: '0 2 0 0',
                            formBind: true,
                            fieldLabel: 'Description',
                            labelAlign: 'top',
                            name: 'CllDes'
                        },
                        {
                            xtype: 'textareafield',
                            flex: 1,
                            margins: '0 0 0 2',
                            fieldLabel: 'Solution',
                            labelAlign: 'top',
                            name: 'CllSln'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            text: 'Save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});