/*
 * File: app/view/TrkMstFlt.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.TrkMstFlt', {
    extend: 'Ext.window.Window',
    alias: 'widget.trkmstflt',

    height: 459,
    id: 'TrkMstFlt',
    width: 716,
    layout: {
        type: 'fit'
    },
    title: 'Filter',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            defaults: [
                {
                    labelWidth: 90,
                    labelSeparator: ' '
                }
            ],
            items: [
                {
                    xtype: 'form',
                    border: 0,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            flex: 1,
                            height: 120,
                            width: 400,
                            defaults: {
                                labelWidth: 90,
                                labelSeparator: ' '
                            },
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Tracking Id',
                                    labelSeparator: ' ',
                                    name: 'TrkIdn'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'User Name',
                                    name: 'UsrNme'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    fieldLabel: 'Date Received',
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            name: 'DteRcvLow'
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            margin: '0 0 0 10',
                                            name: 'DteRcvHgh'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Status',
                                    name: 'CllSts',
                                    displayField: 'CllSts',
                                    forceSelection: true,
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'CllSts',
                                    valueField: 'CllSts'
                                },
                                {
                                    xtype: 'combobox',
                                    id: 'fltCllTyp',
                                    itemId: 'CllTyp',
                                    fieldLabel: 'Type',
                                    name: 'CllTyp',
                                    displayField: 'CllTyp',
                                    forceSelection: true,
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'CllTyp',
                                    valueField: 'CllTyp'
                                },
                                {
                                    xtype: 'combobox',
                                    disabled: true,
                                    itemId: 'CllCtg',
                                    fieldLabel: 'Category',
                                    name: 'CllCtg',
                                    displayField: 'CllCtg',
                                    forceSelection: true,
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'CllCtg',
                                    valueField: 'CllCtg'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Priority',
                                    name: 'CllPri',
                                    displayField: 'CllPri',
                                    forceSelection: true,
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'CllPri'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Class',
                                    name: 'CllCls',
                                    displayField: 'CllCls',
                                    forceSelection: true,
                                    multiSelect: true,
                                    queryMode: 'local',
                                    store: 'CllCls',
                                    valueField: 'CllCls'
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    width: 400,
                                    fieldLabel: ' ',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'HasITR',
                                            boxLabel: 'has an ITR'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'HasBln',
                                            boxLabel: 'has a Bulletin'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    padding: 6,
                                    defaults: {
                                        labelWidth: 84,
                                        labelSeparator: ' '
                                    },
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    title: 'Assignment',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            fieldLabel: 'Group',
                                            name: 'GrpNme',
                                            displayField: 'GrpNme',
                                            multiSelect: true,
                                            queryMode: 'local',
                                            selectOnTab: false,
                                            store: 'CllAsgGrp',
                                            valueField: 'GrpNme'
                                        },
                                        {
                                            xtype: 'combobox',
                                            disabled: true,
                                            fieldLabel: 'Person',
                                            name: 'AsgNme',
                                            displayField: 'AsgNme',
                                            multiSelect: true,
                                            queryMode: 'local',
                                            selectOnTab: false,
                                            store: 'CllAsg',
                                            valueField: 'AsgNme'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            fieldLabel: 'Status',
                                            name: 'AsgSts',
                                            displayField: 'AsgStsDsp',
                                            multiSelect: true,
                                            queryMode: 'local',
                                            selectOnTab: false,
                                            store: 'CllAsgSts',
                                            valueField: 'AsgSts'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            margins: '',
                            height: 327,
                            margin: '0 0 0 10',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: 'Text Search',
                            items: [
                                {
                                    xtype: 'textareafield',
                                    flex: 1,
                                    height: 188,
                                    labelAlign: 'top',
                                    name: 'SchTxt'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    width: 400,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'fieldcontainer',
                                            flex: 1,
                                            width: 400,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            labelSeparator: ' ',
                                            labelWidth: 75,
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    width: 90,
                                                    name: 'SchDes',
                                                    boxLabel: 'Description'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    name: 'SchSln',
                                                    boxLabel: 'Solution'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    flex: 1,
                                                    hidden: true,
                                                    name: 'SchJrn',
                                                    boxLabel: 'Journal'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldcontainer',
                                            flex: 1,
                                            width: 400
                                        }
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    hidden: true,
                                    fieldLabel: 'Journal Type',
                                    labelSeparator: ' ',
                                    labelWidth: 75,
                                    store: 'CllPri'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Apply'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Reset'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});