/*
 * File: app/view/UsrSnI.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.UsrSnI', {
    extend: 'Ext.window.Window',
    alias: 'widget.usrsni',

    height: 150,
    maxHeight: 150,
    minHeight: 150,
    width: 400,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    closable: false,
    title: 'Sign In',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    url: '../shared/PrsSnI.php',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'User Name',
                            name: 'UsrIdn'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Password',
                            name: 'Pwd',
                            inputType: 'password'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'SbmBtn',
                                    text: 'Sign In'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'label',
                                    hidden: true,
                                    html: 'Please correct fields highlighted in <span style="color:red">red</span>',
                                    id: '',
                                    itemId: 'ErrMsg',
                                    style: '{font-size: 12px}'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});