/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'UsrInf'
    ],
    stores: [
        'UsrInf'
    ],
    controllers: [
        'BseCtl',
        'UsrAutCtl'
    ],
    name: 'App',

    launch: function() {
        var Sto = Ext.data.StoreManager.lookup('UsrInf'); 
        var Rcd;
        var UsrCrl;

        Ext.getDoc().dom.title = 'Huhtamaki Standard Template'; 
        var BsePnl = Ext.create('App.view.BsePnl', {
            renderTo: Ext.getBody()
        });
        BsePnl.show();
        BsePnl.down('panel').hide();
        BsePnl.down('toolbar').hide();

        Sto.load();
        Rcd = Sto.first();
        if (Rcd) {
            UsrCrl = Rcd.get('UsrCrl');
        }

        Ext.Ajax.request({
            scope: this,
            url: '../shared/ChkCrl.php',
            method: 'post',
            params: {
                UsrNme: '',
                Pwd: '',
                UsrCrl: UsrCrl
            },    
            success: function(RspJSN){
                Rsp = Ext.JSON.decode(RspJSN.responseText);
                if (Rsp.success === true) {
                    App.getApplication().getController('UsrAutCtl').ChkAut(Rsp.UsrNme,UsrCrl);
                }
                else {
                    var UsrSnI = Ext.create('App.view.UsrSnI', {
                        renderTo: Ext.getBody()
                    });

                    UsrSnI.show();
                }
            },
            failure: function(){
                console.log('Load Error-php');
            }
        });
    }

});
