/*
 * File: app/model/Evt.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.model.Evt', {
    extend: 'Ext.data.Model',
    alias: 'model.evt',

    idProperty: 'Idn',

    fields: [
        {
            name: 'AccIdn',
            sortType: 'asInt',
            type: 'int'
        },
        {
            name: 'Idn',
            sortType: 'asInt',
            type: 'int'
        },
        {
            name: 'EvtGrpIdn',
            sortType: 'asInt',
            type: 'int'
        },
        {
            name: 'Ttl',
            sortType: 'asText',
            type: 'string'
        },
        {
            name: 'Des',
            sortType: 'asText',
            type: 'string'
        },
        {
            dateFormat: '',
            name: 'StrDte',
            sortType: 'asDate',
            type: 'date'
        },
        {
            name: 'StrTme',
            sortType: 'asText',
            type: 'string'
        },
        {
            name: 'EndDte',
            sortType: 'asDate',
            type: 'date'
        },
        {
            name: 'EndTme',
            sortType: 'asText',
            type: 'string'
        },
        {
            name: 'SttAdr',
            sortType: 'asText',
            type: 'string'
        },
        {
            name: 'Cty',
            sortType: 'asText',
            type: 'string'
        },
        {
            name: 'Ste',
            sortType: 'asText',
            type: 'string'
        },
        {
            name: 'PstCde',
            sortType: 'asText',
            type: 'string'
        },
        {
            name: 'IvtTypIdn',
            sortType: 'asInt',
            type: 'int'
        }
    ]
});