/*
 * File: app/model/CusInv.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HuhPtl.model.CusInv', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'YRS'
        },
        {
            name: 'MTH',
            type: 'int'
        },
        {
            name: 'MTHNME'
        },
        {
            name: 'TYP'
        },
        {
            name: 'TYPDES'
        },
        {
            convert: function(v, rec) {
                return rec.get('MTHNME') + ' ' + rec.get('YRS').slice(-2) + '-' + rec.get('TYP');
            },
            name: 'AXSDES1'
        },
        {
            convert: function(v, rec) {
                return rec.get('PRDATRDES') + '-' + rec.get('TYP');
            },
            name: 'AXSDES2'
        },
        {
            convert: function(v, rec) {
                return (rec.get('AMTCG') + rec.get('AMTFS') + rec.get('AMTRT'));
            },
            name: 'AMTHUH',
            type: 'float'
        },
        {
            name: 'AMTCG',
            type: 'float'
        },
        {
            name: 'AMTFS',
            type: 'float'
        },
        {
            name: 'AMTRT',
            type: 'float'
        },
        {
            name: 'PRDATR'
        },
        {
            name: 'PRDATRDES'
        }
    ]
});