/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Evt',
        'EvtGrp',
        'LstVlu'
    ],
    stores: [
        'Evt',
        'EvtGrp',
        'IvtTyp'
    ],
    views: [
        'UsrSnI',
        'BsePnl',
        'EvtGrp',
        'EvtGrpLst',
        'EvtLst'
    ],
    controllers: [
        'BseCtl',
        'UsrSnI',
        'Evt',
        'EvtGrp'
    ],
    name: 'EvtMgr',

    launch: function() {
        Ext.syncRequire(["Ext.ux.RowExpander"]);

        Ext.getDoc().dom.title = 'amps | Events - Event Manager'; 
        var BsePnl = Ext.create('EvtMgr.view.BsePnl', {
            renderTo: Ext.getBody()
        });
        BsePnl.show();

        Ext.Ajax.request({
            url: '../shared/SnISts.php',
            scope: this,
            success: function(RspJSN){
                Rsp = Ext.JSON.decode(RspJSN.responseText);
                if (Rsp.Scs === true) {
                    this.getController('EvtGrp').LodSto(Rsp.AccIdn);
                }
                else {
                    var UsrSnI = Ext.create('EvtMgr.view.UsrSnI', {
                        renderTo: Ext.getBody()
                    });

                    UsrSnI.show();
                }
            },
            failure: function(){
                console.log('Load Error-php');
            }
        });


    }

});
