/*
 * File: apl/controller/BseCtl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.controller.BseCtl', {
    extend: 'Ext.app.Controller',
    alias: 'controller.bsectl',

    AfrRnd: function(abstractcomponent, options) {
        //Ext.Function.defer(function() {
        //    Ext.getBody().unmask();
        //}, 1500, this);
    },

    EvtBtn: function(button, e, options) {
        button.up('viewport').down('panel').getLayout().setActiveItem(0);
    },

    ClkNewGrp: function(button, e, options) {
        //button.up('viewport').down('panel').getLayout().setActiveItem(0);
    },

    ClkNewEvt: function(button, e, options) {
        button.up('viewport').down('panel').getLayout().setActiveItem(1);
    },

    ClkRtn: function(button, e, options) {
        button.up('viewport').down('panel').getLayout().setActiveItem(0);
    },

    ClkSnO: function(button, e, options) {
        Ext.Ajax.request({
            url: '../shared/UsrSnO.php',
            scope: this,
            success: function(RspJSN){
                Rsp = Ext.JSON.decode(RspJSN.responseText);
                if (Rsp.Scs === true) {
                    var UsrSnI = Ext.create('EvtMgr.view.UsrSnI', {
                        renderTo: Ext.getBody()
                    });

                    UsrSnI.show();
                }
                else {
                }
            },
            failure: function(){
                console.log('Load Error-php');
            }
        });
    },

    ShwEvtLst: function(abstractcomponent, options) {
        TBr = abstractcomponent.up('viewport').down('toolbar');
        TBr.child('button[itemId=NewGrpBtn]').setVisible(true);
        TBr.child('button[itemId=NewEvtBtn]').setVisible(true);
    },

    HdeEvtLst: function(abstractcomponent, options) {
        TBr = abstractcomponent.up('viewport').down('toolbar');
        TBr.child('button[itemId=NewGrpBtn]').setVisible(false);
        TBr.child('button[itemId=NewEvtBtn]').setVisible(false);
    },

    ShwEvtDtl: function(abstractcomponent, options) {
        TBr = abstractcomponent.up('viewport').down('toolbar');
        TBr.child('button[itemId=NewIvtBtn]').setVisible(true);
        TBr.child('button[itemId=RtnBtn]').setVisible(true);
    },

    HdeEvtDtl: function(abstractcomponent, options) {
        TBr = abstractcomponent.up('viewport').down('toolbar');
        TBr.child('button[itemId=NewIvtBtn]').setVisible(false);
        TBr.child('button[itemId=RtnBtn]').setVisible(false);
    },

    init: function(application) {
        this.control({
            "evtmgr": {
                afterrender: this.AfrRnd
            },
            "viewport toolbar button[itemId=EvtBtn]": {
                click: this.EvtBtn
            },
            "viewport toolbar button[itemId=NewGrpBtn]": {
                click: this.ClkNewGrp
            },
            "viewport toolbar button[itemId=NewEvtBtn]": {
                click: this.ClkNewEvt
            },
            "viewport toolbar button[itemId=RtnBtn]": {
                click: this.ClkRtn
            },
            "viewport toolbar button[itemId=SnOBtn]": {
                click: this.ClkSnO
            },
            "container[id=EvtLst]": {
                show: this.ShwEvtLst,
                hide: this.HdeEvtLst
            },
            "container[id=EvtDtl]": {
                show: this.ShwEvtDtl,
                hide: this.HdeEvtDtl
            }
        });
    }

});
