/*
 * File: apl/view/BsePnl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.view.BsePnl', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.bsepnl',

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    border: 0,
                    disabled: false,
                    layout: {
                        padding: 1,
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            href: '../evtmgr/app.html',
                            text: 'Events'
                        },
                        {
                            xtype: 'button',
                            href: '../ctcmgr/app.html',
                            text: 'Contacts'
                        },
                        {
                            xtype: 'tbfill',
                            border: 0
                        },
                        {
                            xtype: 'button',
                            text: 'Sign Out'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    border: 0,
                    height: 30
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    border: 0,
                    layout: {
                        type: 'card'
                    },
                    items: [
                        {
                            xtype: 'container'
                        },
                        {
                            xtype: 'container',
                            html: '<h1>Contacts</h1><p>Test</p>'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});