/*
 * File: apl/view/BsePnl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.view.BsePnl', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.bsepnl',

    border: 0,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'toolbar',
                    border: 0,
                    disabled: false,
                    layout: {
                        padding: 1,
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'EvtBtn',
                            text: 'Events',
                            tooltip: 'Open the Events page'
                        },
                        {
                            xtype: 'button',
                            href: '../ctcmgr/app.html',
                            text: 'Contacts',
                            tooltip: 'Open the Contacts page'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'NewGrpBtn',
                            text: 'New Group...',
                            tooltip: 'Create a new event group'
                        },
                        {
                            xtype: 'button',
                            itemId: 'NewEvtBtn',
                            text: 'New Event...',
                            tooltip: 'Create a new event'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'NewIvtBtn',
                            text: 'New Invitation...',
                            tooltip: 'Create a new invitation for the event shown'
                        },
                        {
                            xtype: 'tbfill',
                            border: 0
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            id: '',
                            itemId: 'RtnBtn',
                            icon: 'page-prev.gif',
                            text: 'Return',
                            tooltip: 'Return to Event List panel'
                        },
                        {
                            xtype: 'button',
                            itemId: 'SnOBtn',
                            text: 'Sign Out',
                            tooltip: 'Sign out of the Event Manager'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    border: 0,
                    layout: {
                        type: 'card'
                    },
                    bodyBorder: false,
                    items: [
                        {
                            xtype: 'container',
                            border: 0,
                            id: 'EvtLst',
                            layout: {
                                type: 'border'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 0.25,
                                    region: 'west',
                                    split: true,
                                    margin: 0,
                                    width: 150,
                                    autoScroll: true,
                                    bodyBorder: false,
                                    columnLines: false,
                                    rowLines: false,
                                    store: 'EvtGrp',
                                    viewConfig: {
                                        border: 0,
                                        stripeRows: false
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            border: 0,
                                            dataIndex: 'Ttl',
                                            flex: 1,
                                            text: 'Group'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    region: 'center',
                                    split: false,
                                    autoScroll: true,
                                    store: 'Evt',
                                    viewConfig: {
                                        border: 0
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            border: 0,
                                            dataIndex: 'Ttl',
                                            flex: 1,
                                            menuDisabled: true,
                                            text: 'Event'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            border: 0,
                            id: 'EvtDtl',
                            layout: {
                                type: 'fit'
                            },
                            items: [
                                {
                                    xtype: 'tabpanel',
                                    border: 0,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            title: 'Detail'
                                        },
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            title: 'Invitations'
                                        },
                                        {
                                            xtype: 'panel',
                                            border: 0,
                                            title: 'Options'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});