/*
 * File: apl/view/UsrSnI.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.view.UsrSnI', {
    extend: 'Ext.window.Window',
    alias: 'widget.usrsni',

    height: 158,
    width: 349,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    closable: false,
    title: 'Sign In',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    border: 0,
                    height: 95,
                    id: 'UsrSnIPnl',
                    itemId: 'UsrSnIPnl',
                    width: 262,
                    defaults: {
                        labelWidth: 75,
                        labelSeparator: ' ',
                        enableKeyEvents: true
                    },
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            formBind: true,
                            name: 'UsrNme',
                            fieldLabel: 'User Name'
                        },
                        {
                            xtype: 'textfield',
                            formBind: true,
                            inputType: 'password',
                            name: 'Pwd',
                            fieldLabel: 'Password'
                        },
                        {
                            xtype: 'button',
                            formBind: true,
                            maxWidth: 60,
                            text: 'Sign In'
                        },
                        {
                            xtype: 'label',
                            margins: '10 0 0 0 ',
                            disabled: false,
                            hidden: true,
                            html: 'Invalid User Name and/or Password',
                            style: '{\r\n    color: red;\r\n    font-size: 15px;\r\n}',
                            text: ''
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});