/*
 * File: app/store/Evt.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.store.Evt', {
    extend: 'Ext.data.Store',
    alias: 'store.evt',

    requires: [
        'EvtMgr.model.Evt'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'EvtMgr.model.Evt',
            storeId: 'MyStore1',
            proxy: {
                type: 'rest',
                url: 'data/Evt.php',
                reader: {
                    type: 'json',
                    root: 'Dta',
                    successProperty: 'Scs',
                    totalProperty: 'Ttl'
                }
            },
            sorters: {
                property: 'Ttl'
            }
        }, cfg)]);
    }
});