/*
 * File: app/controller/BseCtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('App.controller.BseCtl', {
    extend: 'Ext.app.Controller',
    alias: 'controller.bsectl',

    refs: [
        {
            ref: 'BsePnl',
            selector: 'bsepnl',
            xtype: 'bsepnl'
        }
    ],

    IniDsp: function() {
        this.getBsePnl().down('panel').show();
        this.getBsePnl().down('toolbar').show();var TabNme;

        var URL = decodeURIComponent(document.URL).split('?');

        if (URL.length > 1) {
            Ext.Object.each(Ext.Object.fromQueryString(URL[1]), function(Key, Vlu) {
                if (Ext.util.Format.lowercase(Key) == 'strpge') {
                    StrPge = Ext.util.Format.lowercase(Vlu);
                }
                if (Ext.util.Format.lowercase(Key) == 'tabnme') {
                    TabNme = Ext.util.Format.lowercase(Vlu);
                }

            });
        }
    }

});
