/*
 * File: app/controller/CogPnlCtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.controller.CogPnlCtl', {
    extend: 'Ext.app.Controller',

    stores: [
        'FleInf'
    ],

    refs: [
        {
            ref: 'CogPnl',
            selector: 'cogpnl'
        }
    ],

    CogDirClk: function(dataview, record, item, index, e, eOpts) {
        if(record.get('FleTyp') != 'File Folder') {
            this.getFleInfStore().load({
                params: { flepth: record.get('id')}
            });
        }
    },

    init: function(application) {
        this.getFleInfStore().on({
            scope: this,
            load : this.FleInfLod
        });

        this.control({
            "cogpnl treepanel": {
                itemclick: this.CogDirClk
            }
        });
    },

    FleInfLod: function(Sto) {
        var Pnl = this.getCogPnl();
        if (Pnl) {
            if (Sto.first()) {
                Pnl.down('form').getForm().loadRecord(Sto.first());
            }
            else {
                Pnl.getForm().reset();
            }
        }
    }

});
