/*
 * File: app/controller/JobPnlCtl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.controller.JobPnlCtl', {
    extend: 'Ext.app.Controller',

    stores: [
        'JobInf',
        'JobInfFle',
        'JobInfLib',
        'JobInfPgm',
        'JobInfSpF'
    ],

    refs: [
        {
            ref: 'JobLst',
            selector: 'joblst'
        },
        {
            ref: 'JobInf',
            selector: 'jobinf'
        },
        {
            ref: 'JobInfSpF',
            selector: 'jobinfspf'
        },
        {
            ref: 'JobInfPgm',
            selector: 'jobinfpgm'
        },
        {
            ref: 'JobInfLib',
            selector: 'jobinflib'
        },
        {
            ref: 'JobInfFle',
            selector: 'jobinffle'
        }
    ],

    SlcChg: function(tablepanel, selections, options) {
        if (selections[0]) {
            this.JobPnlLod(selections[0]);
        }
    },

    JobLstRdy: function(tablepanel, options) {
        if (this.getJobInfStore().count() > 0) {
            tablepanel.getSelectionModel().select(0);
        }
    },

    init: function(application) {
        this.getJobInfStore().on({
            scope: this,
            load : this.JobInfLod
        });

        this.control({
            "joblst": {
                selectionchange: this.SlcChg
            },
            "gridpanel": {
                viewready: this.JobLstRdy
            }
        });
    },

    JobPnlLod: function(Rcd) {
        var Frm = this.getJobInf().getForm();

        Frm.loadRecord(Rcd);
        if (Rcd.data.SBSLIB > '') {
            Frm.findField('SBSQLF').setValue(Rcd.get('SBSLIB') + '/' + Rcd.get('SBS'));
        }
        else {
            Frm.findField('SBSQLF').setValue(Rcd.get('SBS'));
        }

        if (Rcd.data.JBDLIB > '') {
            Frm.findField('JBDQLF').setValue(Rcd.get('JBDLIB') + '/' + Rcd.get('JBD'));
        }
        else {
            Frm.findField('JBDQLF').setValue(Rcd.get('JBD'));
        }


        this.getJobInfLibStore().load({
            params: { 
                Job: Rcd.get('JOB'),
                Usr: Rcd.get('USR'),
                JobNbrA: Rcd.get('JOBNBRA'),
                InfTyp: 'Lib'
            }
        });

        this.getJobInfSpFStore().load({
            params: { 
                Job: Rcd.get('JOB'),
                Usr: Rcd.get('USR'),
                JobNbrA: Rcd.get('JOBNBRA'),
                InfTyp: 'SpF'
            }
        });


        this.getJobInfFleStore().load({
            params: { 
                Job: Rcd.get('JOB'),
                Usr: Rcd.get('USR'),
                JobNbrA: Rcd.get('JOBNBRA'),
                InfTyp: 'Fle'
            }
        });

        /*
        */

        //this.getJobInfPgmStore().load({
        //    params: { 
        //        Job: Rcd.get('JOB'),
        //        Usr: Rcd.get('USR'),
        //        JobNbrA: Rcd.get('JOBNBRA'),
        //        InfTyp: 'Pgm'
        //    }
        //});
    },

    JobInfLod: function(Sto) {
        //if (Sto.getTotalCount() > 0) {
        //    Ext.Function.defer(function() {
        //        if (this.getJobLst()) {
        //            console.log(this.getJobLst().getSelectionModel());
        //            this.getJobLst().getSelectionModel().select(0);
        //        }
        //    }, 5000, this);
        //}
    }

});
