/*
 * File: app/controller/TrkAsgCtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.controller.TrkAsgCtl', {
    extend: 'Ext.app.Controller',

    stores: [
        'TrkAsg'
    ],

    refs: [
        {
            ref: 'TrkAsg',
            selector: 'trkasg'
        }
    ],

    TrkAsgSve: function(button, e, eOpts) {
        this.getTrkAsgStore().sync();
    },

    init: function(application) {
        this.control({
            "trkasg toolbar button[text=Save]": {
                click: this.TrkAsgSve
            }
        });
    }

});
