/*
 * File: app/controller/UsrSnI.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.controller.UsrSnI', {
    extend: 'Ext.app.Controller',

    AftRnr: function(component, eOpts) {
        //component.down('label[itemId=ErrMsg]').setVisible(false);
        component.getForm().findField('UsrIdn').focus(false,200);
    },

    SnIBtnClk: function(button, e, eOpts) {
        //if (button.type == 'submit'){
        Btn = button; 
        Frm = Btn.up('form').getForm();
        //} 
        //else {
        //    Frm = button.getForm();
        //    Btn = button.down('button');
        //}

        if (Frm.isValid()) {
            Frm.submit({
                scope: this,
                success: function(Frm, Rsp) {
                    this.getController('DshBrdCtl').LodSto();
                    Btn.up('window').close();
                },
                failure: function(Frm, Acn) {
                    Btn.nextSibling('label[itemId=ErrMsg]').setVisible(true);
                }
            });
        }
        else {
            Btn.nextSibling('label[itemId=ErrMsg]').setVisible(true);
        }
    },

    init: function(application) {
        this.control({
            "usrsni panel": {
                afterrender: this.AftRnr
            },
            "usrsni form button[itemId=SbmBtn]": {
                click: this.SnIBtnClk
            }
        });
    }

});
