/*
 * File: app/controller/BseCtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.controller.BseCtl', {
    extend: 'Ext.app.Controller',
    alias: 'controller.bsectl',

    stores: [
        'EvtGrp',
        'Evt'
    ],

    RtnBtnClk: function(button, e, eOpts) {
        button.up('viewport').down('panel').getLayout().setActiveItem(0);
    },

    SnOBtnClk: function(button, e, eOpts) {
        Ext.Ajax.request({
            url: '../shared/UsrSnO.php',
            scope: this,
            success: function(RspJSN){
                Rsp = Ext.JSON.decode(RspJSN.responseText);
                if (Rsp.Scs === true) {
                    var UsrSnI = Ext.create('EvtMgr.view.UsrSnI', {
                        renderTo: Ext.getBody()
                    });

                    UsrSnI.show();
                }
                else {
                }
            },
            failure: function(){
                console.log('Load Error-php');
            }
        });
    },

    EvtBtnClk: function(button, e, eOpts) {
        button.up('viewport').down('panel').getLayout().setActiveItem(0);
    },

    init: function(application) {
        this.control({
            "viewport toolbar button[itemId=RtnBtn]": {
                click: this.RtnBtnClk
            },
            "viewport toolbar button[itemId=SnOBtn]": {
                click: this.SnOBtnClk
            },
            "viewport toolbar button[itemId=EvtBtn]": {
                click: this.EvtBtnClk
            }
        });
    }

});
