/*
 * File: app/controller/UsrSnI.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.controller.UsrSnI', {
    extend: 'Ext.app.Controller',
    alias: 'controller.usrsni',

    AfrRnd: function(component, eOpts) {
        component.down('label[itemId=ErrMsg]').setVisible(false);
        component.getForm().findField('UsrNme').focus(false,200);
    },

    SnIBtnClk: function(button, e, eOpts) {
        Btn = button; 
        Frm = Btn.up('form').getForm();

        if (Frm.isValid()) {
            Frm.submit({
                scope: this,
                success: function(Frm, Acn) {
                    this.getController('EvtGrp').LodSto(Acn.result.AccIdn);
                    Btn.up('window').close();
                },
                failure: function(Frm, Acn) {
                    Btn.nextSibling('label[itemId=ErrMsg]').setVisible(true);
                }
            });
        }
        else {
            Btn.nextSibling('label[itemId=ErrMsg]').setVisible(true);
        }
    },

    SpcKey: function(field, e, eOpts) {
        if (e.keyCode == Ext.EventObject.ENTER) {
            this.SnIBtnClk(field.up('form').down('button[itemId=SbmBtn]'));
        }
    },

    TxtFldChg: function(field, newValue, oldValue, eOpts) {
        field.up('panel').down('label[itemId=ErrMsg]').setVisible(false);
    },

    init: function(application) {
        this.control({
            "usrsni panel": {
                afterrender: this.AfrRnd
            },
            "usrsni form button[itemId=SbmBtn]": {
                click: this.SnIBtnClk
            },
            "usrsni textfield": {
                specialkey: this.SpcKey,
                change: this.TxtFldChg
            }
        });
    }

});
