/*
 * File: app/view/AplPrf.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.AplPrf', {
    extend: 'Ext.window.Window',
    alias: 'widget.aplprf',

    height: 417,
    id: 'AplPrfWdw',
    minHeight: 355,
    width: 303,
    autoScroll: true,
    layout: {
        type: 'fit'
    },
    title: 'Prefrences',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: 0,
                    layout: {
                        align: 'stretch',
                        padding: 10,
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            collapsible: true,
                            title: 'Dashboard',
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    flex: 1,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    fieldLabel: 'Tabs',
                                    labelSeparator: ' ',
                                    labelWidth: 35,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'JobTab',
                                            boxLabel: 'Jobs'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'DocTab',
                                            boxLabel: 'Documentation'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'LnkTab',
                                            boxLabel: 'Links'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'CogTab',
                                            boxLabel: 'Cognos'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            collapsible: true,
                            title: 'Tracking Panel',
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    saveDelay: 50,
                                    layout: {
                                        align: 'stretchmax',
                                        type: 'vbox'
                                    },
                                    fieldLabel: 'Tabs',
                                    labelSeparator: ' ',
                                    labelWidth: 35,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'ObjTab',
                                            boxLabel: 'Objects'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'MveTab',
                                            boxLabel: 'Moves'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'PrjTab',
                                            boxLabel: 'Project'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'TskTab',
                                            boxLabel: 'Tasks'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    width: 400,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            name: 'AtoSve',
                                            boxLabel: 'Autosave on selection change'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            collapsed: true,
                            collapsible: true,
                            title: 'Documentation Panel'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});