/*
 * File: app/view/CogPnl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.CogPnl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.cogpnl',

    border: 0,
    layout: {
        type: 'border'
    },
    title: 'Cognos',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    flex: 1,
                    region: 'west',
                    split: true,
                    width: 150,
                    store: 'CogDir',
                    rootVisible: false,
                    useArrows: true,
                    viewConfig: {
                        border: false,
                        itemId: 'CogDir'
                    },
                    columns: [
                        {
                            xtype: 'treecolumn',
                            width: 47,
                            dataIndex: 'FleNme',
                            text: 'File',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'FleTyp',
                            text: 'Type',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'FleSze',
                            text: 'Size',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'LasMod',
                            text: 'Date Modified',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 1,
                    region: 'center',
                    split: true,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 5,
                    title: 'Text File Viewer',
                    items: [
                        {
                            xtype: 'displayfield',
                            name: 'FleNme',
                            fieldStyle: 'font-weight: bold'
                        },
                        {
                            xtype: 'textareafield',
                            flex: 1,
                            name: 'FleTxt',
                            fieldStyle: 'font-family:Courier',
                            readOnly: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});