/*
 * File: app/view/JobInf.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.JobInf', {
    extend: 'Ext.form.Panel',
    alias: 'widget.jobinf',

    border: 0,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    bodyPadding: 10,
    title: 'Detail',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    height: 120,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            name: 'JOB',
                            fieldLabel: 'Job'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'USR',
                            fieldLabel: 'User'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'JOBNBRA',
                            fieldLabel: 'Job Number'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'SBSQLF',
                            fieldLabel: 'Subsystem'
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    flex: 1,
                    height: 120,
                    width: 400,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            name: 'JOBTYP',
                            fieldLabel: 'Job Type'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'JOBSTS',
                            fieldLabel: 'Job Status'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'JOBSTSACV',
                            fieldLabel: 'Active Status'
                        },
                        {
                            xtype: 'displayfield',
                            name: 'JBDQLF',
                            fieldLabel: 'Job Description'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});