/*
 * File: app/view/JobInfFle.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.JobInfFle', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.jobinffle',

    border: 0,
    title: 'Files',
    store: 'JobInfFle',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'FLENME',
                    flex: 1,
                    text: 'File'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'FLELIB',
                    flex: 1,
                    text: 'Library'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'FLETYP',
                    flex: 1,
                    text: 'Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'RELRCDNBR',
                    flex: 0.5,
                    text: 'RRN'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'REDCNT',
                    flex: 0.5,
                    text: 'Read Count'
                }
            ]
        });

        me.callParent(arguments);
    }

});