/*
 * File: app/view/JobInfSpF.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.JobInfSpF', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.jobinfspf',

    border: 0,
    title: 'Spooled Files',
    store: 'JobInfSpF',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SPLFLE',
                    flex: 1,
                    text: 'Spooled File'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SPLFLENBR',
                    flex: 1,
                    text: 'Number'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'OPNDTE',
                    flex: 1,
                    text: 'Open Date'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'OPNTME',
                    flex: 1,
                    text: 'Open Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'FMSTYP',
                    flex: 1,
                    text: 'Form Type'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'OTQ',
                    flex: 1,
                    text: 'OutQ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'OTQLIB',
                    flex: 1,
                    text: 'OutQ Library'
                }
            ]
        });

        me.callParent(arguments);
    }

});