/*
 * File: app/view/JobLst.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.JobLst', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.joblst',

    border: 0,
    store: 'JobInf',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOB',
                    flex: 1,
                    text: 'Job'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'USR',
                    flex: 1,
                    text: 'User'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBNBRA',
                    flex: 1,
                    text: 'Job Number'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SBS',
                    flex: 1,
                    text: 'Subsystem'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SBSLIB',
                    flex: 1,
                    text: 'Subsystem Library'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBTYP',
                    flex: 1,
                    text: 'Job Typ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBSTS',
                    flex: 1,
                    text: 'Job Status'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JOBSTSACV',
                    flex: 1,
                    text: 'Active Status'
                }
            ]
        });

        me.callParent(arguments);
    }

});