/*
 * File: app/view/JobPnl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.JobPnl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.jobpnl',

    requires: [
        'DshBrd.view.JobLst',
        'DshBrd.view.JobInf',
        'DshBrd.view.JobInfSpF',
        'DshBrd.view.JobInfPgm',
        'DshBrd.view.JobInfLib',
        'DshBrd.view.JobInfFle'
    ],

    border: 0,
    layout: {
        type: 'border'
    },
    title: 'Jobs',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'joblst',
                    flex: 2,
                    region: 'center'
                },
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    region: 'south',
                    split: true,
                    border: 0,
                    height: 150,
                    activeTab: 0,
                    tabPosition: 'bottom',
                    items: [
                        {
                            xtype: 'jobinf',
                            itemId: 'JobInfTab'
                        },
                        {
                            xtype: 'jobinfspf',
                            itemId: 'JobInfSpFTab'
                        },
                        {
                            xtype: 'jobinfpgm',
                            itemId: 'JobInfPgmTab'
                        },
                        {
                            xtype: 'jobinflib',
                            itemId: 'JobInfLibTab'
                        },
                        {
                            xtype: 'jobinffle'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});