/*
 * File: app/view/PrjDtl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.PrjDtl', {
    extend: 'Ext.form.Panel',
    alias: 'widget.prjdtl',

    border: 0,
    bodyPadding: 10,
    titleCollapse: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    name: 'project_id',
                    fieldLabel: 'Id'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    name: 'project_name',
                    fieldLabel: 'Name'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    name: 'project_summary',
                    fieldLabel: 'Summary'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    name: 'project_manager',
                    fieldLabel: 'Project Manager'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    name: 'actual_finish',
                    fieldLabel: 'Completion Date'
                }
            ]
        });

        me.callParent(arguments);
    }

});