/*
 * File: app/view/PrjDtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.PrjDtl', {
    extend: 'Ext.form.Panel',
    alias: 'widget.prjdtl',

    border: 0,
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Id',
                    name: 'project_id'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Name',
                    name: 'project_name'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Summary',
                    name: 'project_summary'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Project Manager',
                    name: 'project_manager'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    fieldLabel: 'Completion Date',
                    name: 'actual_finish'
                }
            ]
        });

        me.callParent(arguments);
    }

});