/*
 * File: app/view/PrjTsk.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.PrjTsk', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.prjtsk',

    border: 0,
    store: 'PrjTsk',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        return '<a href=https://www.quickbase.com/db/bazid6rxu?a=er&rid=' + value + ' target="_blank">'+ value +'</a>';
                    },
                    dataIndex: 'task_id',
                    flex: 0.75,
                    text: 'Task Idn'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            return value;
                        }
                    },
                    dataIndex: 'task_name',
                    flex: 4,
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            return value;
                        }
                    },
                    dataIndex: 'status',
                    flex: 1,
                    text: 'Status'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            return value;
                        }
                    },
                    dataIndex: 'assigned_to',
                    flex: 3,
                    text: 'Assigned To'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            return Number(Number(value) / 3600000).toFixed(2);
                        }

                    },
                    align: 'right',
                    dataIndex: 'req_hours',
                    flex: 0.75,
                    text: 'Req Hrs'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            return Number(Number(value) / 3600000).toFixed(2);
                        }
                    },
                    align: 'right',
                    dataIndex: 'epd_hours',
                    flex: 0.75,
                    text: 'EPD Hrs'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            var Dte = new Date(Number(value));
                            return ('0' + (Dte.getMonth()+1)).slice(-2) + '/' + ('0' + Dte.getDate()).slice(-2) + '/' + Dte.getFullYear();
                        }

                    },
                    align: 'center',
                    dataIndex: 'start',
                    flex: 1,
                    text: 'Start Date'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            var Dte = new Date(Number(value));
                            return ('0' + (Dte.getMonth()+1)).slice(-2) + '/' + ('0' + Dte.getDate()).slice(-2) + '/' + Dte.getFullYear();
                        }
                    },
                    align: 'center',
                    dataIndex: 'finish_date',
                    flex: 1,
                    text: 'Finish Date'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if (value == '[object Object]') {
                            return '';
                        }
                        else {
                            return value;
                        }
                    },
                    hidden: true,
                    dataIndex: 'related_resource',
                    flex: 2,
                    text: 'Related Resource'
                }
            ]
        });

        me.callParent(arguments);
    }

});