/*
 * File: app/view/TrkAtc.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.TrkAtc', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.trkatc',

    layout: {
        align: 'stretch',
        type: 'vbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            border: 0,
                            store: 'TrkAtc',
                            viewConfig: {

                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'AtcLnk',
                                    flex: 1,
                                    text: 'Attachment'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'form',
                                    flex: 1,
                                    margins: '5 5 5 5',
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    bodyPadding: 10,
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            name: 'AtcNme',
                                            fieldLabel: 'File Name',
                                            labelSeparator: ' ',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'textfield',
                                            name: 'AtcDes',
                                            fieldLabel: 'Description',
                                            labelSeparator: ' ',
                                            labelWidth: 70
                                        },
                                        {
                                            xtype: 'displayfield',
                                            name: 'AtcLnk',
                                            fieldLabel: 'Link',
                                            labelSeparator: ' ',
                                            labelWidth: 70
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            flex: 1,
                                            dock: 'bottom',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Save'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 0.5,
                                    html: '<div style="font: 30px arial,sans-serif; text-align: center; color: #99BCE8; margin: 20px">Drop Attachment(s) Here</div>',
                                    itemId: 'AtcDrp',
                                    padding: 5,
                                    bodyBorder: false
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});