/*
 * File: app/view/TrkMstLst.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.TrkMstLst', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.trkmstlst',

    border: 0,
    store: 'TrkMstLst',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                preserveScrollOnRefresh: true,
                markDirty: false
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TrkIdn',
                    flex: 1,
                    text: 'Idn'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CllDes',
                    flex: 3,
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CllSts',
                    flex: 1,
                    text: 'Status'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'CllCls',
                    flex: 1,
                    text: 'Class'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ITRNbr',
                    flex: 1,
                    text: 'ITR'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'RcvDte',
                    flex: 1,
                    text: 'Received Date'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'RcvTme',
                    flex: 1,
                    text: 'Received Time'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'UsrNme',
                    flex: 1,
                    text: 'User'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EmlAdrUsr',
                    flex: 2,
                    text: 'Email Address'
                }
            ]
        });

        me.callParent(arguments);
    }

});