/*
 * File: app/view/TrkPnl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.view.TrkPnl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.trkpnl',

    requires: [
        'DshBrd.view.TrkMstLst',
        'DshBrd.view.TrkMstDtl',
        'DshBrd.view.TrkAsg',
        'DshBrd.view.TrkAtc',
        'DshBrd.view.ChgObj',
        'DshBrd.view.ChgRqs',
        'DshBrd.view.PrjDtl',
        'DshBrd.view.PrjTsk'
    ],

    border: 0,
    layout: {
        type: 'border'
    },
    title: 'Tracking',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'trkmstlst',
                    flex: 1,
                    region: 'center'
                },
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    region: 'south',
                    split: true,
                    border: 0,
                    activeTab: 0,
                    tabPosition: 'bottom',
                    items: [
                        {
                            xtype: 'trkmstdtl',
                            itemId: 'DtlTab',
                            title: 'Detail'
                        },
                        {
                            xtype: 'trkasg',
                            itemId: 'AsgTab',
                            title: 'Assignments'
                        },
                        {
                            xtype: 'trkatc',
                            border: 0,
                            itemId: 'AtcTab',
                            title: 'Attachments'
                        },
                        {
                            xtype: 'chgobj',
                            hidden: true,
                            itemId: 'ObjTab',
                            title: 'Objects'
                        },
                        {
                            xtype: 'chgrqs',
                            hidden: true,
                            itemId: 'MveTab',
                            title: 'Moves'
                        },
                        {
                            xtype: 'prjdtl',
                            hidden: true,
                            itemId: 'PrjTab',
                            title: 'Project'
                        },
                        {
                            xtype: 'prjtsk',
                            hidden: true,
                            itemId: 'TskTab',
                            title: 'Tasks'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});