/*
 * File: app/store/CogDir.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.store.CogDir', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'DshBrd.model.FleLst'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: false,
            storeId: 'CogDir',
            model: 'DshBrd.model.FleLst',
            folderSort: true,
            proxy: {
                type: 'ajax',
                extraParams: {
                    pthlst: '../../cogdta|../../coglog',
                    flrlst: 'Data|Logs',
                    dsplst: 'Data [usdso-virgo/prod$/data]|Logs [usdso-virgo/log$]'
                },
                url: 'data/GetDir.php',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});