/*
 * File: app/view/EvtGrpLst.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.view.EvtGrpLst', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.evtgrplst',

    requires: [
        'EvtMgr.view.override.EvtGrpLst'
    ],

    border: false,
    itemId: 'EvtGrpLst',
    margin: 0,
    width: 150,
    autoScroll: true,
    bodyBorder: false,
    columnLines: false,
    rowLines: false,
    store: 'EvtGrp',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                border: 0,
                cls: 'EvtGrp',
                stripeRows: false
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    border: 0,
                    dataIndex: 'Ttl',
                    text: 'Title',
                    flex: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'tbtext',
                            text: 'Groups'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'AddBtn',
                            iconCls: 'add',
                            tooltip: 'Create a new event group'
                        },
                        {
                            xtype: 'button',
                            itemId: 'EdtBtn',
                            iconCls: 'edit',
                            tooltip: 'Edit the selected event group'
                        },
                        {
                            xtype: 'button',
                            itemId: 'DltBtn',
                            iconCls: 'delete',
                            tooltip: 'Delete the selected event group'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});