/*
 * File: app/view/EvtGrpWdw.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.view.EvtGrpWdw', {
    extend: 'Ext.window.Window',
    alias: 'widget.evtgrpwdw',

    height: 220,
    hidden: false,
    width: 500,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    title: 'Event Group',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    border: 0,
                    itemId: 'EvtGrpFrm',
                    maxWidth: 500,
                    width: 500,
                    defaults: {
                        labelWidth: 75,
                        labelSeparator: ' '
                    },
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'label',
                            hidden: true,
                            itemId: 'Acn'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Idn',
                            name: 'Idn'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'AccIdn',
                            name: 'AccIdn'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Title',
                            name: 'Ttl',
                            allowBlank: false,
                            blankText: 'The group title is required.',
                            enforceMaxLength: true,
                            maxLength: 50
                        },
                        {
                            xtype: 'textareafield',
                            fieldLabel: 'Description',
                            name: 'Des'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            dock: 'bottom',
                            defaults: {
                                minWidth: 50
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'SveBtn',
                                    text: 'Save'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'CnlBtn',
                                    margin: '0 0 0 5',
                                    minWidth: 50,
                                    text: 'Cancel',
                                    listeners: {
                                        click: {
                                            fn: me.CnlBtnClk,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'label',
                                    margins: '0 8 0 0',
                                    hidden: true,
                                    html: 'Please correct fields highlighted in <span style="color:red">red</span>',
                                    itemId: 'ErrMsg',
                                    padding: '',
                                    style: '{font-size: 12px;}'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    CnlBtnClk: function(button, e, eOpts) {
        button.up('window').destroy();
    }

});