/*
 * File: app/view/EvtLst.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.view.EvtLst', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.evtlst',

    border: false,
    itemId: 'EvtLst',
    autoScroll: true,
    store: 'Evt',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                border: 0,
                plugins: [
                    Ext.create('Ext.grid.plugin.DragDrop', {
                        ddGroup: 'EvtLst',
                        dragGroup: '',
                        dragText: '{0} selected event{1}'
                    })
                ]
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 496,
                    dataIndex: 'Ttl',
                    menuDisabled: true,
                    text: 'Title',
                    flex: 7
                },
                {
                    xtype: 'datecolumn',
                    width: 75,
                    align: 'center',
                    dataIndex: 'StrDte',
                    menuDisabled: true,
                    text: 'Start Date',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    margin: '',
                    width: 75,
                    align: 'center',
                    dataIndex: 'StrTme',
                    menuDisabled: true,
                    text: 'Start Time',
                    flex: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'tbtext',
                            text: 'Events'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            itemId: 'AddBtn',
                            iconCls: 'add',
                            tooltip: 'Create a new event'
                        },
                        {
                            xtype: 'button',
                            itemId: 'EdtBtn',
                            iconCls: 'edit',
                            tooltip: 'Edit the selected event'
                        },
                        {
                            xtype: 'button',
                            itemId: 'DltBtn',
                            iconCls: 'delete',
                            tooltip: 'Delete the selected event'
                        }
                    ]
                }
            ],
            selModel: Ext.create('Ext.selection.RowModel', {
                mode: 'MULTI'
            })
        });

        me.callParent(arguments);
    }

});