/*
 * File: apl/store/EvtGrp.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvtMgr.store.EvtGrp', {
    extend: 'Ext.data.Store',
    alias: 'store.evtgrp',

    requires: [
        'EvtMgr.model.EvtGrp'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Evt',
            model: 'EvtMgr.model.EvtGrp',
            proxy: {
                type: 'rest',
                url: 'data/EvtGrp.php',
                reader: {
                    type: 'json',
                    root: 'Dta',
                    successProperty: 'Scs',
                    totalProperty: 'Ttl'
                }
            }
        }, cfg)]);
    }
});