/*
 * File: app/model/JobInf.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.model.JobInf', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'JOB'
        },
        {
            name: 'USR'
        },
        {
            name: 'JOBNBRA'
        },
        {
            name: 'SBS'
        },
        {
            name: 'SBSLIB'
        },
        {
            name: 'JOBTYP'
        },
        {
            name: 'JOBSTS'
        },
        {
            name: 'JOBSTSACV'
        },
        {
            name: 'ENTDTM'
        },
        {
            name: 'ACVDTM'
        },
        {
            name: 'JBD'
        },
        {
            name: 'JBDLIB'
        },
        {
            name: 'JBQNME'
        },
        {
            name: 'JBQLIB'
        },
        {
            name: 'JBQPRI'
        },
        {
            name: 'CURUSR'
        }
    ]
});