/*
 * File: app/model/PrjDtl.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.model.PrjDtl', {
    extend: 'Ext.data.Model',

    idProperty: 'task_id',

    fields: [
        {
            name: 'business_sponsor'
        },
        {
            name: 'scorecard'
        },
        {
            name: 'stoplight'
        },
        {
            name: 'organization'
        },
        {
            name: 'documents'
        },
        {
            name: 'project_name'
        },
        {
            name: 'org_priority'
        },
        {
            name: 'pmo_priority'
        },
        {
            name: 'heat_ticket'
        },
        {
            name: 'simplification'
        },
        {
            name: 'project_summary'
        },
        {
            name: 'status_notes'
        },
        {
            name: 'current_status'
        },
        {
            name: 'project_definition'
        },
        {
            name: 'program_manager'
        },
        {
            name: 'project_manager'
        },
        {
            name: 'baseline_start_date'
        },
        {
            name: 'baseline_start_date'
        },
        {
            name: 'capital_project'
        },
        {
            name: 'cep__'
        },
        {
            name: 'status'
        },
        {
            name: 'scr_comment'
        },
        {
            name: 'first_name'
        },
        {
            name: 'last_name'
        },
        {
            name: 'job_title'
        },
        {
            name: 'functional_area'
        },
        {
            name: 'business_phone'
        },
        {
            name: 'mobile_phone'
        },
        {
            name: 'business_fax'
        },
        {
            name: 'customer_email'
        },
        {
            name: 'notes'
        },
        {
            name: 'fax'
        },
        {
            name: 'add_task'
        },
        {
            name: 'tasks'
        },
        {
            name: 'add_issue'
        },
        {
            name: 'issues'
        },
        {
            name: 'customer_name'
        },
        {
            name: 'start_date'
        },
        {
            name: 'projected_end_date'
        },
        {
            name: 'related_project'
        },
        {
            name: 'facility'
        },
        {
            name: 'it_department'
        },
        {
            name: 'scr_flag'
        },
        {
            name: 'apps_stuff'
        },
        {
            name: 'actual_finish'
        },
        {
            name: 'ballpark_duration'
        },
        {
            name: 'copy'
        },
        {
            name: 'predecessor'
        },
        {
            name: 'technical_lead'
        },
        {
            name: 'related_task'
        },
        {
            name: 'project_manager___task___name'
        },
        {
            name: 'project_manager___task___milestone'
        },
        {
            name: 'project_manager___task___finish'
        },
        {
            name: 'date_created'
        },
        {
            name: 'date_modified'
        },
        {
            name: 'project_id'
        },
        {
            name: 'record_owner'
        },
        {
            name: 'last_modified_by'
        }
    ]
});