/*
 * File: app/model/TrkMstFlt.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DshBrd.model.TrkMstFlt', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'TrkIdn'
        },
        {
            name: 'UsrNme'
        },
        {
            name: 'DteRcvLow'
        },
        {
            name: 'DteRcvHgh'
        },
        {
            name: 'CllSts'
        },
        {
            name: 'CllTyp'
        },
        {
            name: 'CllCtg'
        },
        {
            name: 'CllPri'
        },
        {
            name: 'CllCls'
        },
        {
            name: 'SchTxt'
        },
        {
            name: 'SchDes'
        },
        {
            name: 'SchSln'
        },
        {
            name: 'GrpNme'
        },
        {
            name: 'AsgNme'
        },
        {
            name: 'AsgSts'
        },
        {
            name: 'HasITR'
        },
        {
            name: 'HasBln'
        }
    ]
});