/*
 * File: app/controller/PtlCtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HuhPtl.controller.PtlCtl', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'HuhPtl',
            selector: '#HuhPtl',
            xtype: 'huhptl'
        }
    ],

    DaBBtnClk: function(button, e, eOpts) {
        button.up('viewport').down('panel').getLayout().setActiveItem(0);
    },

    AfrRnr: function(component, eOpts) {
        var TabNme;
        var URL = decodeURIComponent(document.URL).split('?');

        if (URL.length > 1) {
            var PrmLst = Ext.Object.fromQueryString(URL[1]);

            Ext.Object.each(Ext.Object.fromQueryString(URL[1]), function(Key, Vlu) {
                if (Ext.util.Format.lowercase(Key) == 'strpge') {
                    TabNme = Ext.util.Format.lowercase(Vlu);
                }

            });
        }

        if (TabNme) {
            HuhPtl.getApplication().getController('SlsPrdCtl').ShwPnl(null,TabNme);
        }
    },

    init: function(application) {
        this.control({
            "button[text=Dashboard]": {
                click: this.DaBBtnClk
            },
            "#CrdDck": {
                afterrender: this.AfrRnr
            }
        });
    }

});
