/*
 * File: app/controller/SlsPrdCtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HuhPtl.controller.SlsPrdCtl', {
    extend: 'Ext.app.Controller',

    stores: [
        'PTcMst',
        'PGrMst',
        'PSbMst',
        'PSzMst',
        'AcMDiv',
        'AcMSeg',
        'AcMRgn',
        'AcMMgr',
        'CusInvT2',
        'CusInvT3',
        'CusInvT4',
        'CusInvT6'
    ],

    refs: [
        {
            ref: 'OptFrm',
            selector: '#SlsPrdPnl form',
            xtype: 'form'
        }
    ],

    ChgRdoGrp: function(field, newValue, oldValue, eOpts) {
        this.UpdPnl(true,true);
    },

    ChgChkBox: function(field, newValue, oldValue, eOpts) {
        if(field.name == 'ShwAct' || field.name == 'ShwBud' || field.name == 'ProBud') {
            this.UpdPnl(false,false);
        }
        else {
            this.UpdPnl(true,true);
        }
    },

    ChgCboBox: function(field, newValue, oldValue, eOpts) {
        if (field.name == 'BegMth' || field.name == 'BegYrs' || field.name == 'EndMth' || field.name == 'EndYrs') {
            this.UpdPnl(true,true);
        }
    },

    ChgPrdTch: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();
        var PGrMst = this.getPGrMstStore();
        var PSbMst = this.getPSbMstStore();
        var PSzMst = this.getPSzMstStore();

        Rcd.set('PrdTch',newValue);
        if (newValue == '*ALL') {
            PGrMst.removeAll();
            Rcd.set('PrdGrp','');
        }
        else if (newValue) {
            PGrMst.load({
                params: { 
                    PrdTch: newValue
                }
            });
        }

        PSbMst.removeAll();
        Rcd.set('PrdSubGrp','');
        PSzMst.removeAll();
        Rcd.set('PrdSiz','');

        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(true,true);
        }
    },

    ChgPrdGrp: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();
        var PSbMst = this.getPSbMstStore();
        var PSzMst = this.getPSzMstStore();

        Rcd.set('PrdGrp',newValue);
        if (newValue == '*ALL' || newValue === '') {
            PSbMst.removeAll();
            Rcd.set('PrdSubGrp','');
        }
        else if (newValue) {
            PSbMst.load({
                params: { 
                    PrdTch: Rcd.get('PrdTch'),
                    PrdGrp: newValue
                }
            });
        }

        PSzMst.removeAll();
        Rcd.set('PrdSiz','');

        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(true,true);
        }
    },

    ChgPrdSubGrp: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();
        var PSzMst = this.getPSzMstStore();

        Rcd.set('PrdSubGrp',newValue);
        if (newValue == '*ALL' || newValue === '') {
            PSzMst.removeAll();
            Rcd.set('PrdSiz','');
        }
        else if (newValue) {
            PSzMst.load({
                params: { 
                    PrdTch: Rcd.get('PrdTch'),
                    PrdGrp: Rcd.get('PrdGrp'),
                    PrdSubGrp: newValue
                }
            });
        }

        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(true,true);
        }
    },

    ChgPrdSiz: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();

        Rcd.set('PrdSiz',newValue);
        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(false,true);
        }
    },

    ChgDivIdn: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();
        var AcMSeg = this.getAcMSegStore();
        var AcMRgn = this.getAcMRgnStore();
        var AcMMgr = this.getAcMMgrStore();

        Rcd.set('DivIdn',newValue);
        if (newValue == '*ALL') {
            AcMSeg.removeAll();
            Rcd.set('BusSeg','');
        }
        else if (newValue) {
            AcMSeg.load({
                params: { 
                    DivIdn: newValue
                }
            });
        }

        AcMRgn.removeAll();
        Rcd.set('RgnCde','');
        AcMMgr.removeAll();
        Rcd.set('AcMCde','');

        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(true,true);
        }
    },

    ChgBusSeg: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();
        var AcMRgn = this.getAcMRgnStore();
        var AcMMgr = this.getAcMMgrStore();

        Rcd.set('BusSeg',newValue);
        if (newValue == '*ALL') {
            AcMRgn.removeAll();
            Rcd.set('RgnCde','');
        }
        else if (newValue) {
            AcMRgn.load({
                params: { 
                    DivIdn: Rcd.get('DivIdn'),
                    BusSeg: newValue
                }
            });
        }

        AcMMgr.removeAll();
        Rcd.set('AcMCde','');

        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(true,true);
        }
    },

    ChgRgnCde: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();
        var AcMMgr = this.getAcMMgrStore();

        Rcd.set('RgnCde',newValue);
        if (newValue == '*ALL') {
            AcMMgr.removeAll();
            Rcd.set('AcMCde','');
        }
        else if (newValue) {
            AcMMgr.load({
                params: { 
                    DivIdn: Rcd.get('DivIdn'),
                    BusSeg: Rcd.get('BusSeg'),
                    RgnCde: newValue
                }
            });
        }

        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(true,true);
        }
    },

    ChgAcMMgr: function(field, newValue, oldValue, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();

        Rcd.set('AcMCde',newValue);
        if((newValue == '*ALL' && oldValue !== '') || (newValue != '*ALL' && newValue > '')) {
            Frm.loadRecord(Rcd);
            this.UpdPnl(false,true);
        }
    },

    SlcRptRow: function(rowmodel, record, index, eOpts) {
        var Frm = this.getOptFrm().getForm();
        var Rcd = Frm.getRecord();
        var AcvTab = this.getOptFrm().down('tabpanel').getActiveTab();
        var Atr;
        var DftVlu = true;

        if (AcvTab.title == 'Sales') {
            Atr = record.get('CUSATR');
            if (Atr != 'ZZZZZ') {
                if (Rcd.get('DivIdn') == '*ALL') {
                    Rcd.set('DivIdn',Atr);
                    DftVlu = false;
                }
                if (Rcd.get('BusSeg') == '*ALL') {
                    Rcd.set('BusSeg',Atr);
                    DftVlu = false;
                }
                if (Rcd.get('RgnCde') == '*ALL') {
                    Rcd.set('RgnCde',Atr);
                    DftVlu = false;
                }
                if (DftVlu) {
                    Rcd.set('AcMCde',Atr);
                }

                Frm.loadRecord(Rcd);
            }
        }
        else {
            Atr = record.get('PRDATR');
            if (Atr != 'ZZZZZ') {
                if (Rcd.get('PrdTch') == '*ALL') {
                    Rcd.set('PrdTch',Atr);
                    DftVlu = false;
                }
                if (Rcd.get('PrdGrp') == '*ALL') {
                    Rcd.set('PrdGrp',Atr);
                    DftVlu = false;
                }
                if (Rcd.get('PrdSubGrp') == '*ALL') {
                    Rcd.set('PrdSubGrp',Atr);
                    DftVlu = false;
                }
                if (DftVlu) {
                    Rcd.set('PrdSiz',Atr);
                }

                Frm.loadRecord(Rcd);
            }
        }
    },

    ChgTabRpt: function(tabPanel, newCard, oldCard, eOpts) {
        var PrdSiz = this.getOptFrm().getForm().findField('PrdSiz');
        if (newCard.title == 'Customer' && Ext.String.trim(PrdSiz.getValue()) > '') {
            PrdSiz.enable();
        } 
        else {
            PrdSiz.disable();
        }

        var AcMCde = this.getOptFrm().getForm().findField('AcMCde');
        if (newCard.title == 'Customer' && Ext.String.trim(AcMCde.getValue()) > '') {
            AcMCde.enable();
        } 
        else {
            AcMCde.disable();
        }
    },

    ChgTabHie: function(tabPanel, newCard, oldCard, eOpts) {
        this.UpdPnl(true,true);
    },

    init: function(application) {
        this.getPTcMstStore().on({
            scope: this,
            load : this.PTcMstLod
        });

        this.getPGrMstStore().on({
            scope: this,
            load : this.PGrMstLod
        });

        this.getPSbMstStore().on({
            scope: this,
            load : this.PSbMstLod
        });

        this.getPSzMstStore().on({
            scope: this,
            load : this.PSzMstLod
        });

        this.getAcMDivStore().on({
            scope: this,
            load : this.AcMDivLod
        });

        this.getAcMSegStore().on({
            scope: this,
            load : this.AcMSegLod
        });

        this.getAcMRgnStore().on({
            scope: this,
            load : this.AcMRgnLod
        });

        this.getAcMMgrStore().on({
            scope: this,
            load : this.AcMMgrLod
        });

        this.control({
            "#SlsPrdPnl radiogroup": {
                change: this.ChgRdoGrp
            },
            "#SlsPrdPnl form checkbox[name!=DspVlu]": {
                change: this.ChgChkBox
            },
            "#SlsPrdPnl form combobox": {
                change: this.ChgCboBox
            },
            "#SlsPrdPnl form combobox[name=PrdTch]": {
                change: this.ChgPrdTch
            },
            "#SlsPrdPnl form combobox[name=PrdGrp]": {
                change: this.ChgPrdGrp
            },
            "#SlsPrdPnl form combobox[name=PrdSubGrp]": {
                change: this.ChgPrdSubGrp
            },
            "#SlsPrdPnl form combobox[name=PrdSiz]": {
                change: this.ChgPrdSiz
            },
            "#SlsPrdPnl form combobox[name=DivIdn]": {
                change: this.ChgDivIdn
            },
            "#SlsPrdPnl form combobox[name=BusSeg]": {
                change: this.ChgBusSeg
            },
            "#SlsPrdPnl form combobox[name=RgnCde]": {
                change: this.ChgRgnCde
            },
            "#SlsPrdPnl form combobox[name=AcMCde]": {
                change: this.ChgAcMMgr
            },
            "#SlsPrdPnl gridpanel[itemId!=SlsRptCus]": {
                select: this.SlcRptRow
            },
            "#SlsPrdPnl tabpanel[itemId!=HieSel]": {
                tabchange: this.ChgTabRpt
            },
            "#SlsPrdPnl tabpanel[itemId=HieSel]": {
                tabchange: this.ChgTabHie
            }
        });
    },

    ShwPnl: function(SrsObj, StrPge) {
        var Rcd = Ext.create('HuhPtl.model.SlsPrdOpt');
        var Frm = Ext.getCmp('SlsPrdPnl').down('form').getForm();
        var HieSelPnl = this.getOptFrm().down('tabpanel');
        var HieSelTab = HieSelPnl.getActiveTab();
        var MthFllNme = ['January','February','March','April','May','June','July','August','September','October','November','December'];
        var Yrs, Mth;
        var ShwCG = true;
        var ShwFS = true;
        var ShwRT = true;
        var ShwAct = true;
        var ShwBud = true;

        if (SrsObj) {
            Yrs = SrsObj.storeItem.get('YRS');
            Mth = SrsObj.storeItem.get('MTH');
            Typ = SrsObj.storeItem.get('TYP');
            BusCde = Ext.getCmp('SlsQdrPnl').down('combobox').getValue();
            ShwCG = (BusCde == 'All Business Units' || BusCde == 'Consumer Goods') ? true : false;
            ShwFS = (BusCde == 'All Business Units' || BusCde == 'Foodservice') ? true : false;
            ShwRT = (BusCde == 'All Business Units' || BusCde == 'Retail') ? true : false;
            ShwAct = (Typ == 'Actual') ? true : false;
            ShwBud = (Typ == 'Budget') ? true : false;
        }
        else {
            var Dte = new Date();
            Yrs = Dte.getFullYear();
            Mth = Dte.getMonth() + 1;
        }

        Frm.findField('DspPnlFlg').setValue(false);
        Rcd.set('ShwCG',ShwCG);
        Rcd.set('ShwFS',ShwFS);
        Rcd.set('ShwRT',ShwRT);
        Rcd.set('BegMth',MthFllNme[Mth-1]);
        Rcd.set('BegYrs',Yrs);
        Rcd.set('EndMth',MthFllNme[Mth-1]);
        Rcd.set('EndYrs',Yrs);
        Rcd.set('PrdTch','*ALL');
        Rcd.set('DivIdn','*ALL');
        Rcd.set('ShwAct',ShwAct);
        Rcd.set('ShwBud',ShwBud);
        Rcd.set('ProBud',true);
        Frm.loadRecord(Rcd);

        Ext.getCmp('CrdDck').getLayout().setActiveItem(1);
        Ext.getCmp('SlsPrdPnl').down('tabpanel').setActiveTab(Ext.getCmp(StrPge));

        if (StrPge == 'prdhie') {
            HieSelPnl.setActiveTab(0);
        }
        else {
            HieSelPnl.setActiveTab(1);
        }

        Frm.findField('DspPnlFlg').setValue(true);
        this.UpdPnl(true,true);
    },

    UpdPnl: function(UpdHie, UpdCus) {
        var Frm = this.getOptFrm().getForm();
        var DspPnlFlg = Frm.findField('DspPnlFlg');
        var HieSelTab = this.getOptFrm().down('tabpanel').getActiveTab();
        var HieRptTabPnl = Ext.getCmp('SlsPrdPnl').down('tabpanel');
        var HieRptTab = HieRptTabPnl.getActiveTab();
        var TblFun;

        if (DspPnlFlg.getValue() == 'true') {
            Frm.updateRecord();
            var Rcd = Frm.getRecord();

            TblFun = 'CUSINVT2';
            if (HieSelTab.title == 'Sales') {
                TblFun = 'CUSINVT8';
            }

            this.getCusInvT2Store().load({
                params: { 
                    ShwCG: Rcd.get('ShwCG'),
                    ShwFS: Rcd.get('ShwFS'),
                    ShwRT: Rcd.get('ShwRT'),
                    BegMth: Ext.Date.getMonthNumber(Rcd.get('BegMth')) + 1,
                    BegYrs: Rcd.get('BegYrs'),
                    EndMth: Ext.Date.getMonthNumber(Rcd.get('EndMth')) + 1,
                    EndYrs: Rcd.get('EndYrs'),
                    PrdTch: Rcd.get('PrdTch'),
                    PrdGrp: Rcd.get('PrdGrp'),
                    PrdSubGrp: Rcd.get('PrdSubGrp'),
                    PrdSiz: Rcd.get('PrdSiz'),
                    DivIdn: Rcd.get('DivIdn'),
                    BusSeg: Rcd.get('BusSeg'),
                    RgnCde: Rcd.get('RgnCde'),
                    AcMCde: Rcd.get('AcMCde'),
                    ShwAct: Rcd.get('ShwAct'),
                    ShwBud: Rcd.get('ShwBud'),
                    ProBud: Rcd.get('ProBud'),
                    DspVlu: Rcd.get('DspVlu'),
                    TblFun: TblFun
                }
            });

            if (UpdHie) {
                if (HieSelTab.title == 'Product') {
                    this.getCusInvT3Store().load({
                        params: { 
                            ShwCG: Rcd.get('ShwCG'),
                            ShwFS: Rcd.get('ShwFS'),
                            ShwRT: Rcd.get('ShwRT'),
                            BegMth: Ext.Date.getMonthNumber(Rcd.get('BegMth')) + 1,
                            BegYrs: Rcd.get('BegYrs'),
                            EndMth: Ext.Date.getMonthNumber(Rcd.get('EndMth')) + 1,
                            EndYrs: Rcd.get('EndYrs'),
                            PrdTch: Rcd.get('PrdTch'),
                            PrdGrp: Rcd.get('PrdGrp'),
                            PrdSubGrp: Rcd.get('PrdSubGrp'),
                            PrdSiz: Rcd.get('PrdSiz'),
                            DspVlu: Rcd.get('DspVlu')
                        }
                    });
                }
                else {
                    this.getCusInvT6Store().load({
                        params: { 
                            ShwCG: Rcd.get('ShwCG'),
                            ShwFS: Rcd.get('ShwFS'),
                            ShwRT: Rcd.get('ShwRT'),
                            BegMth: Ext.Date.getMonthNumber(Rcd.get('BegMth')) + 1,
                            BegYrs: Rcd.get('BegYrs'),
                            EndMth: Ext.Date.getMonthNumber(Rcd.get('EndMth')) + 1,
                            EndYrs: Rcd.get('EndYrs'),
                            DivIdn: Rcd.get('DivIdn'),
                            BusSeg: Rcd.get('BusSeg'),
                            RgnCde: Rcd.get('RgnCde'),
                            AcMCde: Rcd.get('AcMCde'),
                            DspVlu: Rcd.get('DspVlu')
                        }
                    });
                }
            }

            if (UpdCus) {
                TblFun = 'CUSINVT4';
                if (HieSelTab.title == 'Sales') {
                    TblFun = 'CUSINVT7';
                }

                this.getCusInvT4Store().load({
                    params: { 
                        ShwCG: Rcd.get('ShwCG'),
                        ShwFS: Rcd.get('ShwFS'),
                        ShwRT: Rcd.get('ShwRT'),
                        BegMth: Ext.Date.getMonthNumber(Rcd.get('BegMth')) + 1,
                        BegYrs: Rcd.get('BegYrs'),
                        EndMth: Ext.Date.getMonthNumber(Rcd.get('EndMth')) + 1,
                        EndYrs: Rcd.get('EndYrs'),
                        PrdTch: Rcd.get('PrdTch'),
                        PrdGrp: Rcd.get('PrdGrp'),
                        PrdSubGrp: Rcd.get('PrdSubGrp'),
                        PrdSiz: Rcd.get('PrdSiz'),
                        DivIdn: Rcd.get('DivIdn'),
                        BusSeg: Rcd.get('BusSeg'),
                        RgnCde: Rcd.get('RgnCde'),
                        AcMCde: Rcd.get('AcMCde'),
                        DspVlu: Rcd.get('DspVlu'),
                        TblFun: TblFun
                    }
                });
            }

            var PrdGrp = Frm.findField('PrdGrp');
            var PrdSubGrp = Frm.findField('PrdSubGrp');
            var PrdSiz = Frm.findField('PrdSiz');
            if (PrdGrp && PrdGrp.getValue() === '' ) {
                PrdGrp.disable();
            }
            if (PrdSubGrp && PrdSubGrp.getValue() === '' ) {
                PrdSubGrp.disable();
            }
            if (PrdSiz && PrdSiz.getValue() === '' ) {
                PrdSiz.disable();
            }

            var BusSeg = Frm.findField('BusSeg');
            var RgnCde = Frm.findField('RgnCde');
            var AcMCde = Frm.findField('AcMCde');
            if (BusSeg.getValue() === '' ) {
                BusSeg.disable();
            }
            if (RgnCde.getValue() === '' ) {
                RgnCde.disable();
            }
            if (AcMCde.getValue() === '' ) {
                AcMCde.disable();
            }

            if (HieSelTab.title == 'Product') {
                if (HieRptTab.title != 'Chart' && HieRptTab.title != 'Customer') {
                    HieRptTabPnl.setActiveTab(1);
                }
                Ext.getCmp('prdhie').tab.show();
                //        Ext.getCmp('prdhiegph').tab.hide();
                Ext.getCmp('slshie').tab.hide();
                Ext.getCmp('');
            }
            else {
                if (HieRptTab.title != 'Customer') {
                    HieRptTabPnl.setActiveTab(2);
                }
                Ext.getCmp('prdhie').tab.hide();
                //        Ext.getCmp('prdhiegph').tab.hide();
                Ext.getCmp('slshie').tab.show();
            }
        }
    },

    PrsAxsEvt: function(Lbl, Evt, Opt) {

        /*
        var Elm = Ext.get(Lbl.id);

        if (Evt.type == 'mouseover') {
        Elm.set({
        fill: 'red'
        });
        }
        else if (Evt.type == 'mouseout') {
        Elm.set({
        fill: 'black'
        });
        }
        else if (Evt.type == 'click') {

        var Ctl = HuhPtl.getApplication().getController('SlsQdrCtl');
        Ctl.getCusInvT2Store().load({
        params: { 
        Yrs: 2012,
        Mth: Mth
        }
        });    

        Ext.getCmp('CrdDck').getLayout().setActiveItem(1);

        }

        */
    },

    PTcMstLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.PTcMst');

        Rcd.set('PRDTCHHIE','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);
    },

    PGrMstLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.PGrMst');
        var Fld = this.getOptFrm().getForm().findField('PrdGrp');

        Rcd.set('PRDGRPHIE','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);

        Fld.setValue('*ALL');
        Fld.enable();
    },

    PSbMstLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.PSbMst');
        var Fld = this.getOptFrm().getForm().findField('PrdSubGrp');

        Rcd.set('PRDSUBHIE','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);

        Fld.setValue('*ALL');
        Fld.enable();
    },

    PSzMstLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.PSzMst');
        var Fld = this.getOptFrm().getForm().findField('PrdSiz');
        var AcvTab = Ext.getCmp('SlsPrdPnl').down('tabpanel').getActiveTab();

        Rcd.set('PRDSIZHIE','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);

        Fld.setValue('*ALL');
        if (AcvTab.title == 'Customer') {
            Fld.enable();
        }
    },

    AcMDivLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.AcMDiv');

        Rcd.set('DIVIDN','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);
    },

    AcMSegLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.AcMSeg');
        var Fld = this.getOptFrm().getForm().findField('BusSeg');

        Rcd.set('BUSSEG','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);

        Fld.setValue('*ALL');
        Fld.enable();
    },

    AcMRgnLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.AcMRgn');
        var Fld = this.getOptFrm().getForm().findField('RgnCde');

        Rcd.set('RGNCDE','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);

        Fld.setValue('*ALL');
        Fld.enable();
    },

    AcMMgrLod: function(Sto) {
        var Rcd = Ext.create('HuhPtl.model.AcMMgr');
        var Fld = this.getOptFrm().getForm().findField('AcMCde');
        var AcvTab = Ext.getCmp('SlsPrdPnl').down('tabpanel').getActiveTab();

        Rcd.set('ACMCDE','*ALL');
        Rcd.set('DES','*All');
        Sto.add(Rcd);

        Fld.setValue('*ALL');
        if (AcvTab.title == 'Customer') {
            Fld.enable();
        }
    }

});
