/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'CllTyp',
        'CllCtg',
        'CllPri',
        'PrjTsk',
        'PrjDtl',
        'TrkAtc',
        'TrkAsg',
        'TrkMst',
        'ChgObj',
        'ChgRqs',
        'ChgRqsObj',
        'CllCls',
        'CllAsg',
        'CllAsgGrp',
        'CllAsgSts',
        'FleInf',
        'PrfSet',
        'FleDrpInf',
        'FleLst',
        'JobInfLib',
        'JobInfPgm',
        'JobInfFle',
        'JobInf',
        'JobInfSpF',
        'JobInfLog'
    ],
    stores: [
        'CogDir',
        'CllTyp',
        'CllCtg',
        'CllPri',
        'CllSts',
        'PrjTsk',
        'PrjDtl',
        'TrkAtc',
        'TrkAsg',
        'ChgObj',
        'ChgRqs',
        'ChgRqsObj',
        'CllCls',
        'TrkMstLst',
        'CllAsg',
        'TrkMstFlt',
        'CllAsgGrp',
        'CllAsgSts',
        'TrkMstDtl',
        'FleInf',
        'PrfSet',
        'FleDrpInf',
        'AplPrf',
        'JobInf',
        'JobInfSpF',
        'JobInfPgm',
        'JobInfLib',
        'JobInfFle',
        'JobInfLog'
    ],
    views: [
        'DshBrd',
        'JobPnl',
        'DocPnl',
        'LnkPnl',
        'TrkMstLst',
        'TrkPnl',
        'TrkMstDtl',
        'TrkAsg',
        'PrjDtl',
        'PrjTsk',
        'ChgObj',
        'ChgRqs',
        'CogPnl',
        'TrkAtc',
        'DshBrdPrf',
        'FleDrp',
        'JobLst',
        'JobInf',
        'JobInfSpF',
        'JobInfPgm',
        'JobInfLib',
        'JobInfFle'
    ],
    name: 'DshBrd',
    controllers: [
        'JobPnlCtl',
        'TrkMstFltCtl',
        'TrkMstCtl',
        'TrkAtcCtl',
        'DshBrdCtl',
        'CogPnlCtl',
        'TrkAsgCtl'
    ],

    launch: function() {
        Ext.QuickTips.init();
        Ext.getBody().mask('Loading...', 'x-loading-spinner', true);

        var DshBrd = Ext.create('DshBrd.view.DshBrd', {
            renderTo: Ext.getBody()
        });
        DshBrd.show();

        Ext.getBody().unmask();

        Ext.Ajax.timeout = 120000;
    }

});
