/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'CllTyp',
        'CllCtg',
        'CllPri',
        'PrjTsk',
        'PrjDtl',
        'TrkAtc',
        'TrkAsg',
        'TrkMst',
        'ChgObj',
        'ChgRqs',
        'ChgRqsObj',
        'CllCls',
        'CllAsg',
        'CllAsgGrp',
        'CllAsgSts',
        'FleInf',
        'FleDrpInf',
        'FleLst',
        'JobInfLib',
        'JobInfPgm',
        'JobInfFle',
        'JobInf',
        'JobInfSpF',
        'JobInfLog'
    ],
    stores: [
        'CogDir',
        'CllTyp',
        'CllCtg',
        'CllPri',
        'CllSts',
        'PrjTsk',
        'PrjDtl',
        'TrkAtc',
        'TrkAsg',
        'ChgObj',
        'ChgRqs',
        'ChgRqsObj',
        'CllCls',
        'TrkMstLst',
        'CllAsg',
        'TrkMstFlt',
        'CllAsgGrp',
        'CllAsgSts',
        'TrkMstDtl',
        'FleInf',
        'FleDrpInf',
        'AplPrf',
        'JobInf',
        'JobInfSpF',
        'JobInfPgm',
        'JobInfLib',
        'JobInfFle',
        'JobInfLog'
    ],
    views: [
        'DshBrd',
        'JobPnl',
        'DocPnl',
        'LnkPnl',
        'TrkMstLst',
        'TrkPnl',
        'TrkMstDtl',
        'TrkAsg',
        'PrjDtl',
        'PrjTsk',
        'ChgObj',
        'ChgRqs',
        'CogPnl',
        'TrkAtc',
        'FleDrp',
        'JobLst',
        'JobInf',
        'JobInfSpF',
        'JobInfPgm',
        'JobInfLib',
        'JobInfFle',
        'UsrSnI'
    ],
    controllers: [
        'JobPnlCtl',
        'TrkMstFltCtl',
        'TrkMstCtl',
        'TrkAtcCtl',
        'DshBrdCtl',
        'CogPnlCtl',
        'TrkAsgCtl',
        'UsrSnI'
    ],
    name: 'DshBrd',

    launch: function() {
        Ext.getDoc().dom.title = 'IT Dashboard'; 

        Ext.QuickTips.init();
        Ext.getBody().mask('Loading...', 'x-loading-spinner', true);

        var DshBrd = Ext.create('DshBrd.view.DshBrd', {
            renderTo: Ext.getBody()
        });
        DshBrd.show();

        Ext.getBody().unmask();

        Ext.Ajax.timeout = 120000;

        Ext.Ajax.request({
            url: '../shared/SnISts.php',
            scope: this,
            success: function(RspJSN){
                Rsp = Ext.JSON.decode(RspJSN.responseText);

                console.log(Rsp);

                if (Rsp.Scs === true) {
                    this.getController('DshBrdCtl').LodTrkMstLst();
                }
                else {
                    var UsrSnI = Ext.create('DshBrd.view.UsrSnI', {
                        renderTo: Ext.getBody()
                    });

                    UsrSnI.show();
                }
            },
            failure: function(){
                console.log('Load Error-php');
            }
        });
    }

});
