/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'CusInv',
        'PTcMst',
        'PGrMst',
        'PSbMst',
        'PSzMst',
        'SlsPrdOpt',
        'CusInvT3',
        'CusInvT4',
        'AcmMst',
        'AcMBusSeg',
        'AcMAcMCde',
        'AcMRgnCde',
        'CusInvT6'
    ],
    stores: [
        'CusInvT1',
        'CusInvT2',
        'PTcMst',
        'PGrMst',
        'PSbMst',
        'PSzMst',
        'CusInvT3',
        'CusInvT4',
        'AcMDivIdn',
        'AcMBusSeg',
        'AcMRgnCde',
        'AcMAcMCde',
        'CusInvT6'
    ],
    views: [
        'HuhPtl'
    ],
    autoCreateViewport: true,
    controllers: [
        'PtlCtl',
        'SlsQdrCtl',
        'SlsPrdCtl'
    ],
    name: 'HuhPtl',

    launch: function() {
        //this.ChtAxsOvr();

        /*
        var URL = decodeURIComponent(document.URL).split('?');
        var PrmLst;

        if (URL.length > 1) {
        PrmLst = Ext.Object.fromQueryString(URL[1]);

        Ext.Object.each(Ext.Object.fromQueryString(URL[1]), function(Key, Vlu) {
        if (Ext.util.Format.lowercase(Key) == 'strpge') {
        console.log(Key + ":" + Vlu);
        }
        });
        }
        */
    },

    ChtAxsOvr: function() {
        var Apl = this,
            Ctl;

        Ext.chart.axis.Axis.override({
            getOrCreateLabel: function (i, text) {
                var me = this,
                    labelGroup = me.labelGroup,
                    textLabel = labelGroup.getAt(i),
                    surface = me.chart.surface;

                if (textLabel) {
                    if (text != textLabel.attr.text) {
                        textLabel.setAttributes(Ext.apply({
                            text: text
                        }, me.label), true);
                        textLabel._bbox = textLabel.getBBox();
                    }
                }
                else {
                    textLabel = surface.add(Ext.apply({
                        group: labelGroup,
                        type: 'text',
                        x: 0,
                        y: 0,
                        text: text
                    }, me.label));
                    surface.renderItem(textLabel);
                    textLabel._bbox = textLabel.getBBox();

                    if (me.type == 'Category') {
                        if (me.chart.id == 'SlsQdr') {
                            Ctl = Apl.getController('SlsQdrCtl');
                            textLabel.on('mouseover', Ctl.PrsAxsEvt); 
                            textLabel.on('mouseout', Ctl.PrsAxsEvt); 
                            textLabel.on('click', Ctl.PrsAxsEvt);
                        }
                        //                else if (me.chart.id == 'SlsPrd') {
                        //                    Ctl = Apl.getController('SlsPrdCtl');
                        //                }

                    }
                }
                //get untransformed bounding box
                if (me.label.rotation) {
                    textLabel.setAttributes({
                        rotation: {
                            degrees: 0
                        }
                    }, true);
                    textLabel._ubbox = textLabel.getBBox();
                    textLabel.setAttributes(me.label, true);
                } else {
                    textLabel._ubbox = textLabel._bbox;
                }
                return textLabel;
            }
        });
    }

});
