/*
 * File: app/controller/PtlCtl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ptl.controller.PtlCtl', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'BsePnl',
            selector: 'bsepnl',
            xtype: 'bsepnl'
        }
    ],

    DaBBtnClk: function(button, e, eOpts) {
        button.up('viewport').down('panel').getLayout().setActiveItem(0);
    },

    IniDsp: function(AutLst) {
        var TabNme;
        var URL = decodeURIComponent(document.URL).split('?');

        if (URL.length > 1) {
            var PrmLst = Ext.Object.fromQueryString(URL[1]);

            Ext.Object.each(Ext.Object.fromQueryString(URL[1]), function(Key, Vlu) {
                if (Ext.util.Format.lowercase(Key) == 'strpge') {
                    StrPge = Ext.util.Format.lowercase(Vlu);
                }
                if (Ext.util.Format.lowercase(Key) == 'tabnme') {
                    TabNme = Ext.util.Format.lowercase(Vlu);
                }

            });
        }

        if (AutLst.Sls === true) {
            if (StrPge == 'sls') {
                Ext.getCmp('SlsQdrPnl').show();
                if (TabNme) {
                    Ptl.getApplication().getController('SlsPrdCtl').ShwPnl(null,TabNme);
                }
            }
        }
        else {
            Ext.getCmp('SlsQdrPnl').hide();
        }

        if (AutLst.Fin === true) {
            if (StrPge == 'fin') {
                Ext.getCmp('FinQdrPnl').show();
            }
        }
        else {
            Ext.getCmp('FinQdrPnl').hide();
        }

        if (AutLst.Opr === true) {
            if (StrPge == 'opr') {
                Ext.getCmp('OprQdrPnl').show();
            }
        }
        else {
            Ext.getCmp('OprQdrPnl').hide();
        }

        if (AutLst.Sup === true) {
            if (StrPge == 'sup') {
                Ext.getCmp('SupQdrPnl').show();
            }
        }
        else {
            Ext.getCmp('SupQdrPnl').hide();
        }

        this.getBsePnl().down('panel').show();
        this.getBsePnl().down('toolbar').show();
    },

    init: function(application) {
        this.control({
            "button[text=Dashboard]": {
                click: this.DaBBtnClk
            }
        });
    }

});
